### ISSUE TITLE
Change cursor color

### ISSUE THREAD

**Issue by Faydee1220** [stevengharris/MarkupEditor#117]
Does anyone know how to change cursor color?
I already try change webView.tintColor, but not work.
I can't find any color parameter in MarkupEditorUIView.

**Comment by stevengharris** [comment]
You need to do that via CSS or a call to the JavaScript side like you see in MarkupWKWebView. It is specified in markup.css in the #editor section as:

```
#editor {
    caret-color: blue;
}
```

If it's something you want to change dynamically, you could implement the call in MarkupWKWebView to set it, and submit a pull request, or just do it as an extension.

**Comment by Faydee1220** [comment]
Thanks for your help, cursor color can change in file 
`MarkupEditor/Resources/markup.css`

```
#editor {
    caret-color: blue;
}
```

👍👍👍
