### ISSUE TITLE
UIKitDemo unable to build

### ISSUE THREAD

**Issue by JohnKuan** [stevengharris/MarkupEditor#160]
Hi @stevengharris, 

I am trying to test your changes on the Copy and Paste text and I noticed that the UIKitDemo project could not be compiled. SwiftUIDemo works fine.

There are two files that needs to be added to the target membership for UIKitDemo. `SearchBar.swift` and `DocumentPicker.swift`

**Comment by stevengharris** [comment]
I think SearchBar needs to be excluded from the UIKitDemo target. It should only be used by the SearchableContentView that should only be included in the SwiftUIDemo target. I ran into this myself the other day and hadn't fixed to in main.
