### ISSUE TITLE
Unable to add "MarkupEditor" as a Framework, getting error.

### ISSUE THREAD

**Issue by VIJAYARAJSVR** [stevengharris/MarkupEditor#162]
I have  Swift UI macOS Project; I want to add this "MarkupEditor" as a Framework or Package to my project. 

PLEASE FIND THE ATTACHED FILE.

![issue ](https://github.com/stevengharris/MarkupEditor/assets/121444788/50bba32e-00f2-43d8-8253-42c6d0ea40f8)
![issue 1](https://github.com/stevengharris/MarkupEditor/assets/121444788/1a3c60ed-31c0-494b-b3fa-c9917879f66d)

Below are the steps I have followed.

———————————Adding "MarkupEditor" as a Framework——————————————

Step 1: 
  Get the source code file from GitHub, build and copy the "MarkupEditor.framework".

Step 2: 
Created a sample Xcode Mac OS project, build it, then select the target--> Build settings --> under "Framework,Libraries" click the plus button to select the "MarkupEditor.framework".

Step 3: 
Then, build, I got the below Error:

Ignoring file '/Users/web_dev/Desktop/Test Markup/Test Markup/

MarkupEditor.framework/MarkupEditor': found architecture 'arm64', required architecture 'x86_64'

 Could not find module 'MarkupEditor' for target 'x86_64-apple-macos'; found: arm64-apple-ios

**Comment by stevengharris** [comment]
The MarkupEditor is only supported on Mac Catalyst and iOS.

**Comment by VIJAYARAJSVR** [comment]
I created a SwiftUI iOS Project, but I am getting the error below.

Could not find module 'MarkupEditor' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios


Is it possible to support macOS? Please kindly help me.

**Comment by stevengharris** [comment]
You will have to build the MarkupEditor target for the simulator or run the SwiftUIDemo on the simulator (which builds the target). 

I have no plans to support MacOS natively.
