### ISSUE TITLE
MarkupWKWebView initRootFiles triggering twice

### ISSUE THREAD

**Issue by benlong100** [stevengharris/MarkupEditor#169]
Hi Stephen,

I'm having a strange problem in my SwiftUI app. I've got two different places where I'm using a MarkupEditor view. They're not being used at the same time. I got the first one working and assumed it would be an easy process to move the same calls over to the other place where I want it. Unfortunately, the second one has a very strange problem: it seems to be calling the initRootFiles method twice. It gets through initRootFiles, finishes up initForEditing and makes its way through the rest of makeUIView, then it starts up the whole thing again. Along the way, it loses track of SOME of the variables I've passed to it from the MakeEditorView call – it keeps the html but loses the resourcesURL. The loss of that URL causes a crash as it tries to unwrap a nil pointer. Through the process, it never gets around to the onAppear that's attached to MakeEditorView.

The MakeEditor view is nested in amongst some other views. I thought maybe some of them were triggering a re-draw, so I've tried commenting out as many wrapper views as I can, but it doesn't make a difference.

When I trace the flow of the working MarkupEditor, it definitely doesn't return to these same routines more than once, as I'm sure you already know.

I know this is a vague question, without seeing code, but if you've got any ideas about what I could try to track this down, that'd be great!

**Comment by stevengharris** [comment]
My initial guess (which is what I was thinking when you asked about links not working, too) is that the views are somehow sharing a MarkupDelegate. This is in theory okay, but in my case I have a single MarkupToolbar (by using `toolbarLocation = .keyboard` with MarkupEditorView and handling the MarkupToolbar myself), and I found it easier to have each view that contains the MarkupEditor to be the MarkupDelegate for that view. I also specify an id for the containing view based on the id of model object that contains the html content.

Still, the multiple calls to initRootFiles indicates you're instantiating new MarkupWKWebViews somewhere, right? I have mostly just used `let _ = Self._printChanges()` in the body of the view containing MarkupEditorView to figure out what's triggering the change that causes it to be recreated.

**Comment by benlong100** [comment]
The two Markup views are never visible at the same time. Could that still cause a delegate problem? I have them both set to self for a delegate.

**Comment by stevengharris** [comment]
Maybe, if SwiftUI is reusing the view somehow? Maybe just put `.id(UUID())` to prevent that from happening and see if it helps. If they were both visible at the same time, presumably SwiftUI knows they will have different identities, but maybe it's just re-using the view and that is messing things up.

**Comment by benlong100** [comment]
Okay, I went a little farther than that and commented out all of the other instance of the Markup Editor so there's only one copy of any of the code in the app, but it didn't help. Same problem in the same place. Also, that printChanges thing is cool – I didn't know about that. I plugged that in and didn't see that there was any re-draw at all happening between the two init calls. When tracing, it's strange, because after it goes through the initialization and setup the first time, it shows the screen for a moment – not the Markup screen, but the screen as it is when I hit the edit button – and then suddenly heads off into the initialization stuff again.

Don't know if this is helpful, but here's my call to the editor:

`MarkupEditorView(markupDelegate: self, html: $theLibraryComputer.libCompMarkupHTML, whichEditor: "LibComp", whichSkin: theCurrentSkin.currentSkin.skinName, selectAfterLoad: false, resourcesUrl: theLibraryComputer.libCompResourcesURL, id: "Document")
                        
                        .onAppear {
                           MarkupEditor.style = .compact
                           MarkupEditor.toolbarLocation = .keyboard
   //                        MarkupEditor.allowLocalImages = true
//                           print(theLibraryComputer.libCompMarkupHTML)
                        }
                        .onDisappear { MarkupEditor.selectedWebView = nil }
                     MarkupToolbar().makeManaged()`

Within that struct I have these:

` private func setRawText(_ handler: (()->Void)? = nil) {
       MarkupEditor.selectedWebView?.getHtml { html in
          theLibraryComputer.libCompMarkupRawText = attributedString(from: html ?? "")
           handler?()
       }
   }
   
   private func attributedString(from string: String) -> NSAttributedString {
       // Return a monospaced attributed string for the rawText that is expecting to be a good dark/light mode citizen
       var attributes = [NSAttributedString.Key: AnyObject]()
       attributes[.foregroundColor] = UIColor.label
       attributes[.font] = UIFont.monospacedSystemFont(ofSize: StyleContext.P.fontSize, weight: .regular)
       return NSAttributedString(string: string, attributes: attributes)
   }`

And as an extension to that struct, I have this:

`extension theLibraryComputerBit: MarkupDelegate {
   func markupDidLoad(_ view: MarkupWKWebView, handler: (()->Void)?) {
      MarkupEditor.selectedWebView = view
      // We need a reference to this view in order for our save routine to work, so we're storing it in a Global here.
      Globals.theWYSIWYGWebView = view
      setRawText(handler)
   }
   
   func markupInput(_ view: MarkupWKWebView) {
      // This is way too heavyweight, but it suits the purposes of the demo
      setRawText()
   }
   
   /// Callback received after a local image has been added to the document.
   ///
   /// Note the URL will be to a copy of the image you identified, copied to the caches directory for the app.
   /// You may want to copy this image to a proper storage location. For demo, I'm leaving the print statement
   /// in to highlight what happened.
   func markupImageAdded(url: URL) {
      print("Image added from \(url.path)")
   }
}

extension theLibraryComputerBit: FileToolbarDelegate {
   
   func newDocument(handler: ((URL?)->Void)? = nil) {
      MarkupEditor.selectedWebView?.emptyDocument() {
         setRawText()
      }
   }
   
   func existingDocument(handler: ((URL?)->Void)? = nil) {
//      documentPickerShowing.toggle()
   }
   
   func rawDocument() {
//      withAnimation { rawShowing.toggle()}
   }
}`

That's basically all the same stuff I do in the other editor, which works. Obviously, I have some different variable names for the source text and what-not.

**Comment by benlong100** [comment]
Oh, also, after it's done going through its two set-ups, it does show the editor, but without any text in it, and with a toolbar at both the top and the bottom. Well, most of the time. Sometimes it just shows it at the bottom.

**Comment by benlong100** [comment]
Okay, I found the problem. Don't know the solution, but I at least know the cause. I have an Edit button that flips a state variable that results in the MarkupEditor being called. It also flips a "full screen" state variable which causes a bunch of other things on the screen to go away, so that the editor will go full-screen. I do the same thing with the other editor, and it works fine, but with this one, it must be that the change of state to full-screen is somehow triggering that second initialization.

So if I take out the full-screen switch, then the editor appears with my text in it, but it still shows up with a button bar at both the top and bottom. So something strange is still going on.

**Comment by benlong100** [comment]
Okay, after a little more testing... I have a full-screen button that toggles my full-screen state. If I click that after the editor is up, another initialization gets triggered, and when it comes back I no longer have any text, and I'm down to just one menubar(obviously, that part is good). So it looks like anything that triggers a redraw is starting up a fresh MarkupEditor view. So that's sounding again like maybe a delegate problem?

**Comment by stevengharris** [comment]
I don't think so. To eliminate the MarkupEditor and its mechanics from the equation, I sometimes just load a vanilla WKWebView instead of the MarkupWKWebView. Here's an example maybe you could adapt to your full-screen tradeout case between two WKWebViews to see if it suffers from the same problem. In the example, the `date` state changes in the `WKWebViewTest` when you click the button, but the actual `WebView` that is a `UIViewRepresentable` doesn't update, and neither does the `MarkupEditorView`. (You can verify the latter by inserting `let _ = Self.printChanges()` in its body.)

```
import SwiftUI
import MarkupEditor
import WebKit

struct WKWebViewTest: View {
    
    @State var date: Date = Date()
    @State var demoHtml: String = "<h1>This is a MarkupEditorView.</h1>"

    private let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeStyle = .medium
        return formatter
    }()
    
    var body: some View {
        let _ = Self._printChanges()
        Button(action: { date = Date() }, label: { Text(dateFormatter.string(from: date)) })
        WebView()
        MarkupEditorView(html: $demoHtml)
    }

}

struct WebView: UIViewRepresentable {
    let url: URL?
    let html: String?
    
    private let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeStyle = .medium
        return formatter
    }()
    
    init(url: URL? = nil, html: String? = nil) {
        self.url = url
        self.html = html
    }
    
    func makeUIView(context: Context) -> WKWebView  {
        let wkWebView = WKWebView()
        if let url {
            let request = URLRequest(url: url)
            wkWebView.load(request)
        } else if let html {
            wkWebView.loadHTMLString(html, baseURL: nil)
        } else {
            wkWebView.loadHTMLString("<h1>WebView created at \(dateFormatter.string(from: Date()))</h1>", baseURL: nil)
        }
        return wkWebView
    }
    
    func updateUIView(_ uiView: WKWebView, context: Context) {
    }
}
```

I don't really have a feel for what the code looks like where you trade out MarkupEditorViews, but maybe it's not too complicated to just replace the two MarkupEditorViews with this WebView to see what happens. In any case, this is the kind of thing I've done in the past when I'm concerned the MarkupEditorView is doing something funky compared to a vanilla view.

**Comment by benlong100** [comment]
I kind of have your experiment built-in already. Before I bring up the MarkupEditor, there's a regular WKWebView showing in the same place. My edit button just swaps out the regular one for your MarkupEditor. 

My app consists partly of two WKWebViews, each showing different things. There are edit buttons for each, which swap out MarkupEditors to allow for editing. Curiously, the other editor, the one that's working, also has a full-screen button which functions in the same way as this one, and it's working fine. So there must be something in the views that this broken one is wrapped up in that is making it re-initialize upon this redraw.

**Comment by benlong100** [comment]
Okay, got it mostly fixed. The problem was the set of conditionals that I had for keeping track of whether either of the views should be fullscreen resulted in two different calls to the second MarkupEditor – one call for each condition. I re-worked that so that there's only one call and now it's fine.

There's just one remaining odd bit: with the second editor, the first time I call it, it shows a toolbar at the top and bottom of the screen. After that one time, for the rest of the time the app is running, it only draws the correct toolbar. This happens whether I set .toolbar location to either .keyboard or .none. Any thoughts?

**Comment by stevengharris** [comment]
I don't know, sounds like more SwiftUI wackiness. The only place MarkupToolbar is referenced directly is in MarkupEditorView (and to create the inputAccessoryView for the keyboard), and that is where the placement is determined based on MarkupEditor.toolbarLocation.

**Comment by benlong100** [comment]
Okay, thanks. I figured it was SwiftUI wackiness, but there's so MUCH that's wacky about SwiftUI that one hopes that's not the problem. I think you're right, though.

By the way, do I need to do anything to clean up the caches directory? I've been copying images into there, but I haven't been doing any housekeeping with them when I'm done.

**Comment by stevengharris** [comment]
I have not been doing any housekeeping on it myself. They also need to be in place to support undo/redo, so you don't want to remove them too eagerly. The Apple doc says the OS will delete things as needed, and since the local images are all uniquely named, I haven't been worrying about it.
