### ISSUE TITLE
Customizing Buttons

### ISSUE THREAD

**Issue by benlong100** [stevengharris/MarkupEditor#171]
In the InserToolbar file, there is this comment:

`
Note the flow of control. The button actions invoke the `showPluggable[Link/Image/Table]Toolbar` method
/// in the `selectedWebView`. These in turn invoke the MarkupDelegate's `show[Link/Image/Table]Toolbar` method.
`

I can't find any of those methods that you mention. Have those been changed to popover methods?

**Comment by stevengharris** [comment]
Yes, the comment is out of date with the code. s/Toolbar/Popover/
