### ISSUE TITLE
Toolbar justification

### ISSUE THREAD

**Issue by benlong100** [stevengharris/MarkupEditor#172]
Is there any way to have the toolbar center justified, relative to the MarkupEditor, rather than left-justified?

**Comment by stevengharris** [comment]
You can do this by eliminating the ScrollView and the Spacer on the right of the outer HStack in MarkupToolbar. If you still need the Scrollbar (i.e., it's not usable on a phone without it), then you would have to play around some more to find something that works.

**Comment by benlong100** [comment]
Sheesh, how did I miss that - you had it labelled in the code. By the way, deleting that one spacer didn't actually center, I had to leave it on and add a spacer at the other end. It's working great, though!

I keep thinking I've asked my last question, because I'm so close to being finished, but I've got – hopefully – just one more: how to I get rid of the white background in the code style? I took this:

/*    background-color: #F8F8F8; */

out of the code definition in the style sheet, and commented out

/*@media (prefers-color-scheme: dark) {
    code {
        background-color: #808080;
    }
}
 */

But it's still showing up as white.

**Comment by stevengharris** [comment]
It looks okay to me with:

```
code {
    display: block;
    /* background-color: #F8F8F8; */
    border-radius: 3px;
    font-family: 'SF Mono', SFMono-Regular, ui-monospace, 'DejaVu Sans Mono', Menlo, Consolas, monospace;
    white-space: pre;
}
/*
@media (prefers-color-scheme: dark) {
    code {
        background-color: #808080;
    }
}
*/
```

Here is the demo.html with a \<code> block added at the top...

<img width="1003" alt="Screenshot 2023-12-20 at 11 41 32 AM" src="https://github.com/stevengharris/MarkupEditor/assets/1020361/a080f109-c458-4e24-bc6d-aade92cb88c3">

**Comment by benlong100** [comment]
Okay, it must be something somewhere else in my code. Thanks!
