### ISSUE TITLE
Possible strange interaction with other WKWebViews

### ISSUE THREAD

**Issue by benlong100** [stevengharris/MarkupEditor#174]
I have two other WKWebViews running in my SwiftUI app. Suddenly, links in one of them are no longer working. When I look into it I find that the links are firing, but for some reason the link that comes out of navigationAction.request.url is all lowercase. I can see that, in the original source it's camel case, and in my other WKWebView, a link to the same file works, and navigationAction.request.url is not delivering all lowercase.

Is it possible that something in MarkupEditor is changing the links in the navigationActions in my other view? It does this even if I haven't yet opened a MarkupEditor, and this same code was working fine earlier. Unfortunately, I don't know when it broke, so I can't say for sure if it stopped working when I added the MarkupEditor package.

**Comment by stevengharris** [comment]
The lowercasing behavior is very odd, and I cannot think of any place that would occur. I have not been specifying a `wkNavigationDelegate` when creating the MarkupWKWebView, so the clicks in links from it are always handled from within `MarkupDelegate.markupClicked` method. When you specify the `wkNavigationDelegate`, the `MarkupCoordinator.webView(_:decidePolicyFor:decisionHandler:)` will be called-back-to, but when not specified (i.e., the default for MarkupWKWebView), it is never called. I just haven't done enough with the navigation delegate specified to have a feel for what might be going wrong. If you have any kind of example that points in the right direction, I'd be happy to take a look.

**Comment by benlong100** [comment]
Thanks, I think I'll try ripping out the MarkupEditor and see if I still have the problem. Then I'll at least know if this yours is a tree I should be barking up.

**Comment by benlong100** [comment]
Okay, it's not directly your code. In my app I'm linking to local files only. The Link popover in the MarkupEditor requires file:// on the front of links to local files. For some reason, in one of my web views, this works fine, in the other it converts my links to lowercase. I'm getting around this now by taking the results from the popover and stripping out file://. So now everything's fine. Well, everything except that gnawing itch of wanting to know why this is happening, but I have enough other bugs to worry about that I can skip that one.
