### ISSUE TITLE
Can't track changes in text editor 

### ISSUE THREAD

**Issue by NourGweda1** [stevengharris/MarkupEditor#176]
Can't track changes in the text editor, 
the text stays the same even after editing.
Need help fixing this so I can see the changes I make in the editor.

**Comment by stevengharris** [comment]
See the flow in DemoContentView starting at markupInput. All interaction with the MarkupWKWebView is async. You need to use getHtml to pull the changed text.

**Comment by NourGweda1** [comment]
hello, 
I Tried to run the swiftui code but it didn't show any result regarding the onChange of rich text , here's a snap shot of what I edited in the code to see any result 

<img width="867" alt="Screenshot 2024-01-02 at 2 52 04 PM" src="https://github.com/stevengharris/MarkupEditor/assets/129954039/03588fd8-11ce-48b9-bfef-d1a1456e395b">

**Comment by stevengharris** [comment]
See https://github.com/stevengharris/MarkupEditor/issues/81
