### ISSUE TITLE
Pasting html text sometimes gets truncated

### ISSUE THREAD

**Issue by JohnKuan** [stevengharris/MarkupEditor#179]
From what I have noticed, there is a difference in behavior with the paste logic when there are existing text and when it is a blank content.

In the UIKitDemo project,

https://github.com/stevengharris/MarkupEditor/assets/4402214/d9bbe8d6-67ae-485c-befe-85f6cfad73b0

It seems that only the first item is copied, while the others are truncated.

**Comment by JohnKuan** [comment]
Looking from Safari Web Inspector, the issue lies in `beforeTarget.parentNode.insertBefore(nextSib, beforeTarget);`, where the error "null is not an object (evaluating 'beforeTarget.parentNode')" is being thrown from. 

`const beforeTarget = anchorNode.nextElementSibling;` is giving null for `beforeTarget` and the `anchorNode.outerHTML` is `<p><br></p>` for an emptied web view.

**Comment by stevengharris** [comment]
Fixing some of the HTML pasting issues I notices when working on https://github.com/stevengharris/MarkupEditor/issues/128 is what has taken a little longer. I think this is fixed, but I will double-check. Thanks.

**Comment by stevengharris** [comment]
I had not fixed this in the work I was doing in https://github.com/stevengharris/MarkupEditor/issues/128, but I have it fixed now and will fold it in there.
