### ISSUE TITLE
The real machine runs an error

### ISSUE THREAD

**Issue by wisepmlin** [stevengharris/MarkupEditor#2]
Thread 1: signal SIGABRT
System version： 15.2

**Comment by stevengharris** [comment]
I don't have any way to even guess what this is about without more information.

**Comment by wisepmlin** [comment]
It's nice to see the open source editor you offer. I have been running the kit normally, but I am testing the stability of the software. I found that when I clicked New Page, sometimes I couldn't get the focus in the input box, and I needed to try to click multiple times.
The second point: I am trying to add ordinals to the edited text, I can only add sequence symbols one by one in a paragraph way, I can't select multiple paragraphs, and add sequences to multiple paragraphs at once.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steve ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 凌晨2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stevengharris/MarkupEditor] The real machine runs an error (Issue #2)





 
I don't have any way to even guess what this is about without more information.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wisepmlin** [comment]
I was testing the toolkit stability on the iPad side and found that the table could not be added on the iPad side because I could not select the matrix of the table. During the interaction, I tried many kinds of gestures, but none of them responded to the selected table. But the ui rendered on the mac catalyst can be added tables by mouse movement.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevengharris/MarkupEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 凌晨2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevengharris/MarkupEditor] The real machine runs an error (Issue #2)





 
I don't have any way to even guess what this is about without more information.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stevengharris** [comment]
I will open another issue about the table creation UI on iPad/iOS
