### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by wisepmlin** [stevengharris/MarkupEditor#3]
0x1052f8578 <+8>: b.lo 0x10528598； <+40>   -》〉》Thread 1: signal SIGABRT

**Comment by stevengharris** [comment]
I can see in the GitHub notification I was forwarded (altho not in what appears above) that this is a result of not finding the MarkupEditor.framework file. Obviously from the next issue you filed, you managed to fix or work around the issue. Do you know what caused it and then fixed it? If it's something I did on packaging, I'd like to know. Thx.
