### ISSUE TITLE
Pasteboard alert on iOS 16

### ISSUE THREAD

**Issue by sdtaheri** [stevengharris/MarkupEditor#77]
Hello,

Is there a way to disable the paste alerts that are thrown at initialization? 

I know I can disable the alert in the app settings as of iOS 16.1, but I really prefer it to not be there in the first place. I can't ask all my users to go there.

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-09 at 17 48 10](https://user-images.githubusercontent.com/57771530/206716950-3e4e826b-5b3e-4633-ab49-ead0750b7f78.png)

**Comment by sdtaheri** [comment]
Thanks. These are the changes:
https://sarunw.com/posts/uipasteboard-privacy-change-ios16/

[Here](https://github.com/stevengharris/MarkupEditor/blob/556b7825e91f9d894ceeccf1e6d082b0e1afc0e9/MarkupEditor/MarkupWKWebView.swift#L876) is the culprit in code. It reads the `data` and `string` everytime and causes the alert to pop up continuously.

```
//...
        } else if pasteboard.contains(pasteboardTypes: ["public.html"]) {
            if let data = pasteboard.data(forPasteboardType: "public.html"), String(data: data, encoding: .utf8) != nil {
                // We have HTML, which we will have to sanitize before pasting
                return .Html
            }
        } else if pasteboard.string != nil {
            // We have a string that we can paste
            return .Text
        }
//...
```

**Comment by stevengharris** [comment]
Thanks for the details. I was out of town but will take a look this week. I was not sensitized to it because I am primarily using it on a Mac and using Ctrl-C/Ctrl-V.

**Comment by stevengharris** [comment]
Thanks again for raising the issue and for the debugging to locate the problem!

**Comment by sdtaheri** [comment]
@stevengharris Thank you for resolving it this fast.

**Comment by haemi** [comment]
I still get this all the time when selecting text... am I missing something?

**Comment by stevengharris** [comment]
It shouldn't be happening if you are using `main`. Does it happen in SwiftUIDemo?
